Feature/17539 17567 group service bd refactor
Vinnichenko-Ivan/backend-hits-comand pull request #25
Opened 2023-03-04 14:32 UTC by Millniker

2023-03-04 15:40 UTC, AlekseyFeofilov commented on src/main/java/ru/hits/hitsback/timetable/controller/GroupController.java
> +        return ResponseEntity.status(200).build();
Здесь тоже ResponseEntity.ok(); При чём без build, ну и, понятное дело, без статуса, потому что ok - это и есть 200
И везде в подобных местах

2023-03-04 15:40 UTC, AlekseyFeofilov commented on src/main/java/ru/hits/hitsback/timetable/exception/GroupAlreadyExistException.java
> +public class GroupAlreadyExistException extends RuntimeException{
Добавь Is: GroupIsAlreadyExistException

2023-03-04 15:40 UTC, AlekseyFeofilov commented on src/main/java/ru/hits/hitsback/timetable/service/GroupService.java
> +}
Ох, ну что за no empty line стиль?) Глаз выколи - одна единственная пустая строчка во всём файле и то там, где не нужна) Тебя надо на третий модуль к первокурсникам, чтобы ты вспомнил, где надо пустые строки оставлять. У тебя это не только здесь, я думал просто игнорировать, но здесь прям вообще треш, так даже Ваня не пишет)

2023-03-04 15:40 UTC, AlekseyFeofilov commented on src/main/java/ru/hits/hitsback/timetable/controller/ErrorControllerAdvice.java
> +        return handleCustomException(HttpStatus.BAD_REQUEST, "group.bad-request");
Вместо group.bad-request лучше писать что-то более определенное. Например, group.same-number. А то так получается, что если, например, возникнет другая причина, по которой этот номер нельзя указать (например, он равен 666)), то это снова как бы bad-request, но сообщение-то должно быть другое

2023-03-04 15:40 UTC, AlekseyFeofilov commented on src/main/resources/messages.properties
> +group.bad-request = group bad request
Аналогично описание должно быть более осмысленным, иначе вообще непонятно, что не так с группой. Представь, что ты фронт, и бек тебе возвращает "хуёвый запрос". Почему?? Напиши "group with this number is already exist". Посмотри для примера на другие мои сообщения об ошибках

2023-03-04 15:40 UTC, AlekseyFeofilov commented on src/main/java/ru/hits/hitsback/timetable/service/GroupService.java
> +        return group.getDto().getGroupIdDto();
Ты проверял это? Выглядит так, будто это всегда будет возвращать null

2023-03-04 15:40 UTC, AlekseyFeofilov commented on src/main/java/ru/hits/hitsback/timetable/service/GroupService.java
> +            throw new GroupAlreadyExistException();
А вот это ты проверял? Я почти уверен, что ты никогда не сможешь сменить группу с таким кодом. Ты достаёшь из бд группу, а потом проверяешь, есть ли группа с таким номером в бд. Судя по тому, что ты её достал и даже проверил на null - она там есть))) Ты, вероятно, хотел написать groupDto.getNumber(). Если так и я нигде не ошибся, то как ты проверял или почему ты не проверял? Сервисы надо обязательно тестить

2023-03-04 15:40 UTC, AlekseyFeofilov commented on src/main/java/ru/hits/hitsback/timetable/controller/GroupController.java
> +        groupService.editGroup(groupDto);
Почему ты не исправил ошибки из предыдущего пул реквеста? Я же тебе писал про названия методов. Иди в прошлый пул реквест и исправляй тот код ревью

2023-03-04 15:45 UTC, Millniker commented on src/main/java/ru/hits/hitsback/timetable/controller/GroupController.java
> +        groupService.editGroup(groupDto);
если ты про пулл Feature/17539 group service, то там ничего нет

2023-03-04 15:52 UTC, Millniker commented on src/main/java/ru/hits/hitsback/timetable/service/GroupService.java
> +        return group.getDto().getGroupIdDto();
Проверял, возвращает id.

2023-03-04 15:53 UTC, Millniker commented on src/main/java/ru/hits/hitsback/timetable/service/GroupService.java
> +            throw new GroupAlreadyExistException();
Я тестил сервисы, эту ошибку я уже под конец добавил и реально опечатался, там groupDto.getNumber(), без нее все работает. Тут признаю, мой косяк

2023-03-04 16:01 UTC, Millniker commented on src/main/java/ru/hits/hitsback/timetable/controller/GroupController.java
> +        return ok(groupService.fetchGroups());
Ну это я уже взял из AuthorisationController, поэтому точно так же и написал

2023-03-04 16:01 UTC, Millniker commented on src/main/java/ru/hits/hitsback/timetable/controller/GroupController.java
> +        return ResponseEntity.status(200).build();
Здесь аналогичная ситуация

2023-03-04 16:02 UTC, Millniker commented on src/main/java/ru/hits/hitsback/timetable/controller/ErrorControllerAdvice.java
> +        return handleCustomException(HttpStatus.BAD_REQUEST, "group.bad-request");
Окей, этого не знал, я в целом думал, что это для дефолтных названий, а не чтобы свои ошибки писать

2023-03-04 16:02 UTC, Millniker commented on src/main/resources/messages.properties
> +group.bad-request = group bad request
Испралено

2023-03-04 16:03 UTC, Millniker commented on src/main/java/ru/hits/hitsback/timetable/exception/GroupAlreadyExistException.java
> +public class GroupAlreadyExistException extends RuntimeException{
Не очень понимаю о чем ты

2023-03-04 16:05 UTC, Millniker commented on src/main/java/ru/hits/hitsback/timetable/controller/GroupController.java
> +        return ResponseEntity.status(200).build();
Ну и плюс он не позволяет оставлять пустой ResponseEntity.ok();

2023-03-04 16:13 UTC, AlekseyFeofilov commented on src/main/java/ru/hits/hitsback/timetable/controller/GroupController.java
> +        return ok(groupService.fetchGroups());
А, ну ладно, это оно и есть, просто из импорта подтянулось 
<img width="539" alt="image" src="https://user-images.githubusercontent.com/98858896/222916729-9785dccd-411a-4846-8e02-c120c10fd63f.png">

2023-03-04 16:14 UTC, AlekseyFeofilov commented on src/main/java/ru/hits/hitsback/timetable/controller/GroupController.java
> +        return ResponseEntity.status(200).build();
А вот здесь напиши ResponseEntity.ok(); Ване тоже стоило бы так сделать. А то, что build() требует - ок, тогда оставь с ним

2023-03-04 16:15 UTC, AlekseyFeofilov commented on src/main/java/ru/hits/hitsback/timetable/exception/GroupAlreadyExistException.java
> +public class GroupAlreadyExistException extends RuntimeException{
GroupAlreadyExistException -> GroupIsAlreadyExistException

2023-03-04 16:15 UTC, AlekseyFeofilov commented on src/main/java/ru/hits/hitsback/timetable/controller/ErrorControllerAdvice.java
> +        return handleCustomException(HttpStatus.BAD_REQUEST, "group.bad-request");
Это то, что будет вылетать тому, кто вызвал запрос нашей апишке, в ответе

2023-03-04 16:19 UTC, AlekseyFeofilov commented on src/main/java/ru/hits/hitsback/timetable/service/GroupService.java
> +            throw new GroupAlreadyExistException();
Хорошо

2023-03-04 16:21 UTC, AlekseyFeofilov commented on src/main/java/ru/hits/hitsback/timetable/controller/GroupController.java
> +        groupService.editGroup(groupDto);
<img width="977" alt="image" src="https://user-images.githubusercontent.com/98858896/222917115-1d9a2da7-1df7-4ced-848b-97e1c2abf02a.png">

2023-03-04 16:29 UTC, Millniker commented on src/main/java/ru/hits/hitsback/timetable/controller/GroupController.java
> +        groupService.editGroup(groupDto);
ничего против твоих названий не имею, если бы spring не ругался, то назвал бы точь в точь, но так как он не дает этого сделать, то было два варианта, заменить первое слово синонимом, либо удалить приставку Group, мне показалось, что с синонимом останется больше информативности о методе, но мне не принципиально, исправил на твои варианты

2023-03-04 16:30 UTC, Millniker commented on src/main/java/ru/hits/hitsback/timetable/service/GroupService.java
> +}
Это уже какой то кодстайл буллинг пошел

2023-03-04 16:39 UTC, Millniker commented on src/main/java/ru/hits/hitsback/timetable/controller/ErrorControllerAdvice.java
> +        return handleCustomException(HttpStatus.BAD_REQUEST, "group.bad-request");
Done

2023-03-04 16:40 UTC, Millniker commented on src/main/java/ru/hits/hitsback/timetable/exception/GroupAlreadyExistException.java
> +public class GroupAlreadyExistException extends RuntimeException{
Done

2023-03-04 16:48 UTC, AlekseyFeofilov commented on src/main/resources/messages.properties
> +group.same-number = group with this number is already exist
Не, фигня название, давай group.used-number

2023-03-04 16:48 UTC, AlekseyFeofilov commented on src/main/java/ru/hits/hitsback/timetable/controller/GroupController.java
> +        return ResponseEntity.ok(groupService.fetchGroups());
Договорились же, что можешь оставить, раз этот тот же метод) Ну ладно, оставь уже, всё равно без разницы. Но вообще, лучше так, как по мне, потому что так читается лучше

2023-03-05 06:05 UTC, Vinnichenko-Ivan requested changes

2023-03-05 06:05 UTC, Vinnichenko-Ivan commented on src/main/java/ru/hits/hitsback/timetable/configuration/WebSecurityConfig.java
> +                .requestMatchers(HttpMethod.POST,"/" + BASE_URL + GROUP_URL).hasAuthority("ScheduleWriter")
Убирай, я все в другом пуле настроил

2023-03-05 06:09 UTC, Millniker commented on src/main/java/ru/hits/hitsback/timetable/configuration/WebSecurityConfig.java
> +                .requestMatchers(HttpMethod.POST,"/" + BASE_URL + GROUP_URL).hasAuthority("ScheduleWriter")
Только у тебя почему то только зареганый чел может смотреть группы, а не любой ноу нейм

2023-03-05 06:16 UTC, AlekseyFeofilov commented on src/main/java/ru/hits/hitsback/timetable/exception/UserAlreadyInGroupException.java
> +public class UserAlreadyInGroupException extends RuntimeException{
UserIsAlreadyInGroupException))

2023-03-05 06:16 UTC, AlekseyFeofilov commented on src/main/java/ru/hits/hitsback/timetable/exception/UserAlreadyInGroupException.java
> +public class UserAlreadyInGroupException extends RuntimeException{
Что он вообще здесь делает? Где ты его используешь?

2023-03-05 06:17 UTC, Millniker commented on src/main/java/ru/hits/hitsback/timetable/exception/UserAlreadyInGroupException.java
> +public class UserAlreadyInGroupException extends RuntimeException{
Оу, соре, из другой ветки случайно утащил

2023-03-05 06:28 UTC, AlekseyFeofilov approved these changes

2023-03-05 06:32 UTC, merged